pipeline {
    agent {
        docker 'maven:3.6.3-jdk-11'
    }
    stages {
        stage('Hello World') {
            steps {
                script {
                    echo 'Hello, World!'
                }
            }
        }
    }
}